---
title: "The Multivariate normal distribution"
output: html_notebook
---


```{r}
library(here)
library(mvtnorm)
library(GGally)
library(MVN)
library(dplyr)
library(readr)
```


```{r}
(mu <- c(2,3,4))
```
```{r}
(Sigma <- diag(1:3) + 1)
```
```{r}
x <- rmvnorm(1000, mu, Sigma)
dim(x)
```
```{r}
ggpairs(as.data.frame(x))
```

```{r}
y <- rnorm(1000)
w <- rbinom(1000,1,1/2)
z <- cbind((2*w-1)*y, y)
ggpairs(as.data.frame(z))
```
```{r}
mvn(z)
```

```{r}
mvn(z, mvnTest="mardia", univariateTest="SW")  # Methods we've discussed.
```
```{r}
zp1 <- z%*%c(1,-1)
plot(density(zp1))
```

```{r}
xp1 <- x%*%c(1,-1,0)
plot(density(xp1))
```

```{r}
xp2 <- x%*%rnorm(3) # A random projection.
plot(density(xp2))
```


```{r}
ovens <- read_csv(here("datasets","ovens.csv"))
```

```{r}
ggpairs(ovens)
```

```{r}
mvn(ovens)
```

```{r}
mvn(ovens, mvnTest="mardia", univariateTest="SW") # Methods we've discussed.
```

```{r}
ovens4 <- ovens^(1/4) # Take 4th root.
ggpairs(ovens4)
```

```{r}
mvn(ovens4)
```

```{r}
mvn(ovens4, mvnTest="mardia", univariateTest="SW") # Methods we've discussed.
```
```{r}

```
