---
title: "ZZSC5855 --- Factor analysis"
author:
- Pavel Krivitsky
- Department of Statistics
- University of New South Wales
output:
  html_document:
    df_print: paged
  pdf_document: default
  html_notebook: default
---


# Packages
```{r}
library(here)
library(dplyr)
library(readr)
# stats is loaded by default
library(psych)
library(GGally)
```


# Challenges
Recall the dataset `pizza.csv`, containing nutritional data from a variety of pizza brands:

`brand`
: Pizza brand (class label)

`id`
: Sample analysed

`prot`
: Amount of protein per 100 grams in the sample

`fat`
: Amount of fat per 100 grams in the sample

`ash`
: Amount of ash per 100 grams in the sample

`sodium`
: Amount of sodium per 100 grams in the sample

`carb`
: Amount of carbohydrates per 100 grams in the sample

`cal`
: Amount of calories per 100 grams in the sample


We will, again, focus on brand A:
```{r}
pizzaA <- read_csv(here("datasets","pizza.csv")) %>% filter(brand=="A") %>% select(-brand)
ggpairs(pizzaA)
```

### Task 1: Perform the factor analysis on these data; what is the adequate number of factors?


### Task 2: What do these factors appear to represent?
